export const LIMA_DEMO_GRAPH = {
  nodes: [
    {
      id: 'plaza-san-martin',
      label: 'Plaza San Martin',
      district: 'Centro de Lima',
      kind: 'landmark',
      point: { latitude: -12.0511, longitude: -77.0346 },
    },
    {
      id: 'parque-exposicion',
      label: 'Parque de la Exposicion',
      district: 'Centro de Lima',
      kind: 'landmark',
      point: { latitude: -12.0613, longitude: -77.0365 },
    },
    {
      id: 'estadio-nacional',
      label: 'Estadio Nacional',
      district: 'Lima',
      kind: 'mobility-hub',
      point: { latitude: -12.0675, longitude: -77.0336 },
    },
    {
      id: 'pueblo-libre',
      label: 'Pueblo Libre',
      district: 'Pueblo Libre',
      kind: 'district',
      point: { latitude: -12.0748, longitude: -77.0627 },
    },
    {
      id: 'san-miguel',
      label: 'San Miguel',
      district: 'San Miguel',
      kind: 'district',
      point: { latitude: -12.0778, longitude: -77.0861 },
    },
    {
      id: 'callao-airport',
      label: 'Aeropuerto Jorge Chavez',
      district: 'Callao',
      kind: 'mobility-hub',
      point: { latitude: -12.0219, longitude: -77.1143 },
    },
    {
      id: 'san-isidro',
      label: 'San Isidro Financiero',
      district: 'San Isidro',
      kind: 'district',
      point: { latitude: -12.0967, longitude: -77.0365 },
    },
    {
      id: 'javier-prado',
      label: 'Javier Prado',
      district: 'San Borja',
      kind: 'mobility-hub',
      point: { latitude: -12.0899, longitude: -76.9962 },
    },
    {
      id: 'miraflores-kennedy',
      label: 'Parque Kennedy',
      district: 'Miraflores',
      kind: 'landmark',
      point: { latitude: -12.1211, longitude: -77.0292 },
    },
    {
      id: 'larcomar',
      label: 'Larcomar',
      district: 'Miraflores',
      kind: 'landmark',
      point: { latitude: -12.1311, longitude: -77.0306 },
    },
    {
      id: 'barranco',
      label: 'Barranco',
      district: 'Barranco',
      kind: 'district',
      point: { latitude: -12.1459, longitude: -77.0217 },
    },
    {
      id: 'surco-higuereta',
      label: 'Ovalo Higuereta',
      district: 'Surco',
      kind: 'mobility-hub',
      point: { latitude: -12.1319, longitude: -76.9958 },
    },
    {
      id: 'la-molina',
      label: 'La Molina',
      district: 'La Molina',
      kind: 'district',
      point: { latitude: -12.0895, longitude: -76.9445 },
    },
  ],
  edges: [
    {
      id: 'e-centro-exposicion',
      from: 'plaza-san-martin',
      to: 'parque-exposicion',
      corridor: 'Av. Nicolas de Pierola',
      distanceMeters: 1400,
      speedKph: 22,
      congestionLevel: 0.72,
      bidirectional: true,
    },
    {
      id: 'e-exposicion-estadio',
      from: 'parque-exposicion',
      to: 'estadio-nacional',
      corridor: 'Paseo de la Republica',
      distanceMeters: 950,
      speedKph: 28,
      congestionLevel: 0.52,
      bidirectional: true,
    },
    {
      id: 'e-estadio-san-isidro',
      from: 'estadio-nacional',
      to: 'san-isidro',
      corridor: 'Via Expresa',
      distanceMeters: 3900,
      speedKph: 48,
      congestionLevel: 0.42,
      bidirectional: true,
    },
    {
      id: 'e-san-isidro-miraflores',
      from: 'san-isidro',
      to: 'miraflores-kennedy',
      corridor: 'Av. Arequipa',
      distanceMeters: 3600,
      speedKph: 32,
      congestionLevel: 0.58,
      bidirectional: true,
    },
    {
      id: 'e-miraflores-larcomar',
      from: 'miraflores-kennedy',
      to: 'larcomar',
      corridor: 'Av. Larco',
      distanceMeters: 1300,
      speedKph: 22,
      congestionLevel: 0.44,
      bidirectional: true,
    },
    {
      id: 'e-larcomar-barranco',
      from: 'larcomar',
      to: 'barranco',
      corridor: 'Costa Verde',
      distanceMeters: 2300,
      speedKph: 46,
      congestionLevel: 0.28,
      bidirectional: true,
    },
    {
      id: 'e-barranco-surco',
      from: 'barranco',
      to: 'surco-higuereta',
      corridor: 'Av. Republica de Panama',
      distanceMeters: 3600,
      speedKph: 34,
      congestionLevel: 0.5,
      bidirectional: true,
    },
    {
      id: 'e-surco-javier-prado',
      from: 'surco-higuereta',
      to: 'javier-prado',
      corridor: 'Av. Aviacion',
      distanceMeters: 4800,
      speedKph: 36,
      congestionLevel: 0.48,
      bidirectional: true,
    },
    {
      id: 'e-javier-prado-la-molina',
      from: 'javier-prado',
      to: 'la-molina',
      corridor: 'Av. Javier Prado Este',
      distanceMeters: 5900,
      speedKph: 44,
      congestionLevel: 0.38,
      bidirectional: true,
    },
    {
      id: 'e-san-isidro-javier-prado',
      from: 'san-isidro',
      to: 'javier-prado',
      corridor: 'Av. Javier Prado',
      distanceMeters: 4400,
      speedKph: 30,
      congestionLevel: 0.67,
      bidirectional: true,
    },
    {
      id: 'e-estadio-pueblo-libre',
      from: 'estadio-nacional',
      to: 'pueblo-libre',
      corridor: 'Av. Brasil',
      distanceMeters: 3900,
      speedKph: 26,
      congestionLevel: 0.61,
      bidirectional: true,
    },
    {
      id: 'e-pueblo-libre-san-miguel',
      from: 'pueblo-libre',
      to: 'san-miguel',
      corridor: 'Av. La Marina',
      distanceMeters: 2700,
      speedKph: 34,
      congestionLevel: 0.46,
      bidirectional: true,
    },
    {
      id: 'e-san-miguel-airport',
      from: 'san-miguel',
      to: 'callao-airport',
      corridor: 'Av. Faucett',
      distanceMeters: 7600,
      speedKph: 42,
      congestionLevel: 0.54,
      bidirectional: true,
    },
    {
      id: 'e-centro-pueblo-libre',
      from: 'plaza-san-martin',
      to: 'pueblo-libre',
      corridor: 'Av. Bolivia',
      distanceMeters: 4300,
      speedKph: 24,
      congestionLevel: 0.68,
      bidirectional: true,
    },
    {
      id: 'e-san-miguel-san-isidro',
      from: 'san-miguel',
      to: 'san-isidro',
      corridor: 'Circuito Costa Verde',
      distanceMeters: 6500,
      speedKph: 52,
      congestionLevel: 0.34,
      bidirectional: true,
    },
    {
      id: 'e-miraflores-surco',
      from: 'miraflores-kennedy',
      to: 'surco-higuereta',
      corridor: 'Av. Benavides',
      distanceMeters: 5200,
      speedKph: 31,
      congestionLevel: 0.57,
      bidirectional: true,
    },
    {
      id: 'e-javier-prado-miraflores',
      from: 'javier-prado',
      to: 'miraflores-kennedy',
      corridor: 'Av. Angamos',
      distanceMeters: 4300,
      speedKph: 30,
      congestionLevel: 0.62,
      bidirectional: true,
    },
  ],
};
